name: Provision AWS Lambda function

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:                                            
  release:                                       
    name: Release                                
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout                                  
        uses: actions/checkout@v4
      
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  

      - name: Configure AWS credentials                          
        uses: aws-actions/configure-aws-credentials@v4         
        with:                                                    
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}        
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup to build Go program
        uses: actions/setup-go@v5
      
      - name: Build Go program
        run: GOARCH=amd64 GOOS=linux go build -o ./bootstrap main.go

      - name: Zip the AWS lambda function
        run: zip ./deployments/deployment.zip bootstrap

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Provision resources
        run: cd deployments && terraform init && terraform apply -auto-approve
        
